print('ASCII value of H is:', ord('H'))
print('ASCII value of 1 is:', ord('1'))
print('ASCII value of \\n is:', ord('\n'))
print('ASCII of e is :', ord('e'))
print('W->', ord('W'))
print('0->', ord('0'))
print('*->', ord('*'))
print(ord('l'))
print(ord('i'))
print(ord('s'))
print(ord('t'))
